version: '3.8'

services:
  psql-db:
    container_name: dev-psql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - dev-psql-pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - psql

volumes:
  dev-psql-pg:

networks:
  psql:
    driver: bridge
    external: true

